version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: scripts
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./import:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge